/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx,js,jsx}'],
  theme: {
    extend: {
      borderRadius: {
        lg: 'var(--radius-lg)',
        md: 'var(--radius-md)',
        sm: 'var(--radius-sm)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        inner: 'var(--radius-inner)',
        full: 'var(--radius-full)',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          50: 'hsl(var(--primary-50))',
          100: 'hsl(var(--primary-100))',
          200: 'hsl(var(--primary-200))',
          300: 'hsl(var(--primary-300))',
          400: 'hsl(var(--primary-400))',
          500: 'hsl(var(--primary-500))',
          600: 'hsl(var(--primary-600))',
          700: 'hsl(var(--primary-700))',
          800: 'hsl(var(--primary-800))',
          900: 'hsl(var(--primary-900))',
          950: 'hsl(var(--primary-950))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
          50: 'hsl(var(--secundary-50))',
          100: 'hsl(var(--secundary-100))',
          200: 'hsl(var(--secundary-200))',
          300: 'hsl(var(--secundary-300))',
          400: 'hsl(var(--secundary-400))',
          500: 'hsl(var(--secundary-500))',
          600: 'hsl(var(--secundary-600))',
          700: 'hsl(var(--secundary-700))',
          800: 'hsl(var(--secundary-800))',
          900: 'hsl(var(--secundary-900))',
          950: 'hsl(var(--secundary-950))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
          50: 'hsl(var(--accent-50))',
          100: 'hsl(var(--accent-100))',
          200: 'hsl(var(--accent-200))',
          300: 'hsl(var(--accent-300))',
          400: 'hsl(var(--accent-400))',
          500: 'hsl(var(--accent-500))',
          600: 'hsl(var(--accent-600))',
          700: 'hsl(var(--accent-700))',
          800: 'hsl(var(--accent-800))',
          900: 'hsl(var(--accent-900))',
          950: 'hsl(var(--accent-950))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
        text: {
          50: 'hsl(var(--text-50))',
          100: 'hsl(var(--text-100))',
          200: 'hsl(var(--text-200))',
          300: 'hsl(var(--text-300))',
          400: 'hsl(var(--text-400))',
          500: 'hsl(var(--text-500))',
          600: 'hsl(var(--text-600))',
          700: 'hsl(var(--text-700))',
          800: 'hsl(var(--text-800))',
          900: 'hsl(var(--text-900))',
          950: 'hsl(var(--text-950))',
        },
        warning: {
          50: 'hsl(var(--warning-50))',
          100: 'hsl(var(--warning-100))',
          200: 'hsl(var(--warning-200))',
          300: 'hsl(var(--warning-300))',
          400: 'hsl(var(--warning-400))',
          500: 'hsl(var(--warning-500))',
          600: 'hsl(var(--warning-600))',
          700: 'hsl(var(--warning-700))',
          800: 'hsl(var(--warning-800))',
          900: 'hsl(var(--warning-900))',
          950: 'hsl(var(--warning-950))',
        },
        danger: {
          50: 'hsl(var(--darnger-50))',
          100: 'hsl(var(--darnger-100))',
          200: 'hsl(var(--darnger-200))',
          300: 'hsl(var(--darnger-300))',
          400: 'hsl(var(--darnger-400))',
          500: 'hsl(var(--darnger-500))',
          600: 'hsl(var(--darnger-600))',
          700: 'hsl(var(--darnger-700))',
          800: 'hsl(var(--darnger-800))',
          900: 'hsl(var(--darnger-900))',
          950: 'hsl(var(--darnger-950))',
        },
        success: {
          50: 'hsl(var(--suscess-50))',
          100: 'hsl(var(--suscess-100))',
          200: 'hsl(var(--suscess-200))',
          300: 'hsl(var(--suscess-300))',
          400: 'hsl(var(--suscess-400))',
          500: 'hsl(var(--suscess-500))',
          600: 'hsl(var(--suscess-600))',
          700: 'hsl(var(--suscess-700))',
          800: 'hsl(var(--suscess-800))',
          900: 'hsl(var(--suscess-900))',
          950: 'hsl(var(--suscess-950))',
        },
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
